### ISSUE TITLE
Installation process?

### ISSUE THREAD

**Issue by OrkoHunter** [TwistingTwists/sms#1]
We need to configure the `.py` files first after installation right? Can't there be just a single file where we fill our configuration (or python fills them for us after prompting) and the sms library uses the file for configuration?

This will enable the installation using `pip` or `easy_install`.

**Comment by TwistingTwists** [comment]
Cool Idea! On it.

**Comment by TwistingTwists** [comment]
Added configuration file in `/data/config.json`. Thanks @OrkoHunter.
